version: "3.8"

services:
  app:
    image: product-app
    ports:
      - "9091:9091"
    depends_on:
      - mysql
    networks:
      - app-network
    volumes:
      - app_data:/data/springboot-app

  mysql:
    image: mysql:8.0.13
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sbms
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  app-network:

volumes:
  mysql_data:
  app_data: